SELECT a.NOMBRE, a.APELLIDO1, a.APELLIDO2, tc.TITULO
FROM ALUMNOS a
JOIN ASISTIR S USING(NIF)
JOIN CURSOS c USING (N_CURSO)
JOIN TIPOS_CURSO tc USING (cod_curso)
ORDER BY 2,3,1,4;

SELECT TITULO, N_CURSO, p.NOMBRE, COD_CURSO
FROM TIPOS_CURSO
JOIN CURSOS c USING(COD_CURSO)
JOIN PROFESORES p ON(p.nif = NIF_PROFESOR);

SELECT NOMBRE, APELLIDO1, APELLIDO2
FROM ALUMNOS a
NATURAL JOIN ASISTIR s;

SELECT t1.TITULO, t1.DURACION,t2.TITULO,t2.DURACION
FROM TIPOS_CURSO t1
CROSS JOIN TIPOS_CURSO t2
WHERE t1.TITULO='Windows 2023 II'
        AND t1.DURACION<=t2.DURACION
        AND t1.TITULO!=t2.TITULO    --TITULO TIENE UNA RESTRICCIÓN UK. SI NO FUERA UNICO, COMPARAR CON LA CLAVE
ORDER BY 1;