SELECT NOMBRE, APELLIDO1, APELLIDO2, EDAD
FROM ALUMNOS
WHERE EDAD=(
        SELECT MAX(EDAD)
        FROM ALUMNOS
    );

SELECT NOMBRE, APELLIDO1, APELLIDO2, EDAD, ABS(EDAD-(
        SELECT MAX(EDAD)
        FROM ALUMNOS
    )) DIFERENCIA_DE_EDAD
FROM ALUMNOS;

SELECT NOMBRE, APELLIDO1, APELLIDO2, COUNT(*) AS CURSOS_QUE_HACE
FROM ALUMNOS a
JOIN ASISTIR s USING (NIF)
JOIN CURSOS c USING (N_CURSO)
JOIN TIPOS_CURSO t USING (COD_CURSO)
GROUP BY NOMBRE, APELLIDO1, APELLIDO2, NIF
HAVING COUNT(*)>1
ORDER BY 2,3,1;


SELECT NOMBRE, APELLIDO1, APELLIDO2
FROM ALUMNOS a
JOIN ASISTIR s USING (NIF)
JOIN CURSOS c USING (N_CURSO)
JOIN TIPOS_CURSO t USING (COD_CURSO)
WHERE UPPER(t.TITULO) LIKE'MECANO%' AND (NOMBRE, APELLIDO1, APELLIDO2)

        IN (SELECT NOMBRE, APELLIDO1, APELLIDO2
        FROM ALUMNOS a
        JOIN ASISTIR s USING (NIF)
        JOIN CURSOS c USING (N_CURSO)
        JOIN TIPOS_CURSO t USING (COD_CURSO)
        WHERE UPPER(t.TITULO) LIKE'WINDOWS%')

ORDER BY 2,3,1;

