--PIEZAS QUE ESTEN EN EL ALMACEN 1 Y 2:
--USANDO IN
SELECT TIPO, MODELO, N_ALMACEN
FROM PIEZAS p
JOIN EXISTENCIAS e USING (TIPO, MODELO)
WHERE N_ALMACEN=1
AND (TIPO,MODELO) IN (
    SELECT TIPO, MODELO
    FROM PIEZAS p
    JOIN EXISTENCIAS e USING (TIPO, MODELO)
    WHERE N_ALMACEN=2 );
--USANDO EXISTS
SELECT TIPO, MODELO, N_ALMACEN
FROM EXISTENCIAS e
WHERE N_ALMACEN=1
AND EXISTS (
    SELECT *
    FROM EXISTENCIAS e2
    WHERE N_ALMACEN=2 AND e.MODELO=e2.MODELO AND e.TIPO=e2.TIPO);


--PIEZAS QUE SOLO ESTAN EN EL ALMACEN 1
SELECT TIPO, MODELO, N_ALMACEN
FROM PIEZAS p
JOIN EXISTENCIAS e USING (TIPO, MODELO)
MINUS
SELECT TIPO, MODELO, N_ALMACEN
FROM PIEZAS p
JOIN EXISTENCIAS e USING (TIPO, MODELO)
WHERE (TIPO,MODELO) IN (
    SELECT TIPO, MODELO
    FROM PIEZAS p
    JOIN EXISTENCIAS e USING (TIPO, MODELO)
    WHERE N_ALMACEN!=1 );

