--EJERCICIO1
SELECT TO_CHAR( ,'"El primer jueves del mes de mayo de 1950 fue el dia " dd " de mayo"')
FROM DUAL;
--EJERCICIO2
SELECT ID_ACCESO, UPPER(USUARIO)
FROM ACCESOS
WHERE ((MOD(ID_ACCESO,2))!=0) AND MOD(ID_ACCESO,7)=0;

--EJERCICIO3
SELECT USUARIO, TO_CHAR(FECHA,'FMdd/mm/yyyy') AS FECHA,DIRECCION_IP,

       CASE
       WHEN DIRECCION_IP LIKE '192.168.32.%' OR DIRECCION_IP LIKE '192.168.41%' THEN 'Red de alumnos'
       WHEN DIRECCION_IP LIKE '192.168.2.%' AND NOT (DIRECCION_IP LIKE '192.168.32.%' OR DIRECCION_IP LIKE '192.168.41%') THEN 'Red de profesores'
       WHEN DIRECCION_IP LIKE '192.168%' AND NOT (DIRECCION_IP LIKE '192.168.32.%' OR DIRECCION_IP LIKE '192.168.41%' OR DIRECCION_IP LIKE '192.168.2.%') THEN 'Otra red local'
       WHEN DIRECCION_IP IS NULL THEN 'Red de sistema'
       WHEN DIRECCION_IP IS NOT NULL AND NOT DIRECCION_IP LIKE '192.168.32.%' AND NOT DIRECCION_IP LIKE '192.168.41%' AND NOT DIRECCION_IP LIKE '192.168.2.%' AND NOT DIRECCION_IP LIKE '192.168%' THEN 'Red externa'

END AS TIPORED
FROM ACCESOS;

--EJERCICIO4
SELECT USUARIO, TO_CHAR(FECHA,'fmDay dd"," hh:mi:ss') AS FECHA_CONEXION, HOST
FROM ACCESOS
WHERE USUARIO IS NOT NULL AND LOWER(USUARIO) NOT LIKE 'sys' AND LOWER(EXTRACT(MONTH FROM FECHA)) NOT LIKE 'enero' AND EXTRACT(HOUR FROM FECHA) NOT LIKE 8-12
ORDER BY 2 DESC;

--EJERCICIO5
SELECT USUARIO, REGEXP_SUBSTR(USUARIO,1, REGEXP_INSTR(USUARIO, '.')) AS NOMBRE
FROM ACCESOS;

