--EJERCICIO1
SELECT d.COD_DIA DIAS, COUNT(COD_TREN) TRENES
FROM DIAS d
JOIN TRENES t USING (COD_TREN)
JOIN PARADAS p USING (COD_TREN)
JOIN ESTACIONES e USING (COD_EST)
WHERE UPPER(LOCALIDAD)='PALENCIA'
GROUP BY COD_DIA
ORDER BY TRENES DESC;

--EJERCICIO2
SELECT COD_TREN
FROM ESTACIONES
JOIN PARADAS USING (COD_EST)
WHERE UPPER(LOCALIDAD) = 'VILLALBA DE GUADARRAMA'
AND COD_TREN IN (
    SELECT COD_TREN
    FROM ESTACIONES
    JOIN PARADAS USING (COD_EST)
    WHERE UPPER(LOCALIDAD) = 'VENTA DE BAÑOS'
    );

--EJERCICIO3
SELECT d.COD_TREN
FROM DIAS d
WHERE d.COD_DIA = '1' AND NOT d.COD_TREN IN(
    SELECT d.COD_TREN
    FROM DIAS d
    WHERE d.COD_DIA = '7'
    );

--EJERCICIO4
SELECT COD_TREN CÓDIGO_TREN, COD_TIPO TIPO, TO_CHAR(HORA, 'HH:mm') HORAS,
        CASE COD_DIA
           WHEN 1 THEN 'Lunes'
           WHEN 2 THEN 'Martes'
           WHEN 3 THEN 'Miercoles'
           WHEN 4 THEN 'Jueves'
           WHEN 5 THEN 'Viernes'
           WHEN 6 THEN 'Sabado'
           WHEN 7 THEN 'Domingo'
           END DIA
FROM TRENES t
JOIN DIAS d USING (COD_TREN)
JOIN PARADAS p USING (COD_TREN)
JOIN ESTACIONES e USING (COD_EST)
WHERE UPPER(e.NOMBRE) = 'MIRANDA DE EBRO';