--EJERCICIO1

CREATE VIEW VPARTIDOS AS
SELECT EC.ID_EQUIPO ,ec.NOMBRE, FECHA,
       GOLES_CASA GOLES_FAVOR, GOLES_FUERA GOLES_CONTRA,
       ef.ID_EQUIPO ID_EQUIPO_CONTRA, ef.NOMBRE nombre_contra
FROM EQUIPOS ec
JOIN PARTIDOS p ON (ec.ID_EQUIPO=p.ID_EQUIPO_CASA)
JOIN EQUIPOS ef ON (ef.ID_EQUIPO=p.ID_EQUIPO_FUERA)
UNION ALL
SELECT ef.ID_EQUIPO ,ef.NOMBRE, FECHA,
       GOLES_FUERA GOLES_FAVOR, GOLES_CASA GOLES_CONTRA,
       ec.ID_EQUIPO ID_EQUIPO_CONTRA, ec.NOMBRE nombre_contra
FROM EQUIPOS ec
JOIN PARTIDOS p ON (ec.ID_EQUIPO=p.ID_EQUIPO_CASA)
JOIN EQUIPOS ef ON (ef.ID_EQUIPO=p.ID_EQUIPO_FUERA);

SELECT NOMBRE, ID_EQUIPO, SUM(GOLES_CONTRA) AS GOLES_CONTRA, SUM(GOLES_FAVOR) AS GOLES_FAVOR
FROM VPARTIDOS
GROUP BY NOMBRE, ID_EQUIPO;

--EJERCICIO2

CREATE VIEW v_pichichi (ID_JUGADOR, JUGADOR, GOLES) AS
    SELECT ID_JUGADOR ,NOMBRE, COUNT(*) GOLES
FROM JUGADORES j
JOIN GOLES g USING (id_jugador)
GROUP BY ID_JUGADOR, NOMBRE
HAVING COUNT(*)=(
    SELECT MAX(COUNT(*))
    FROM JUGADORES j
    JOIN GOLES g USING (id_jugador)
    GROUP BY  NOMBRE
    );

SELECT JUGADOR FROM V_PICHICHI;

--EJERCICIO3
--ACABAR

CREATE OR REPLACE VIEW V_GOLES (ID_EQUIPO,GOLES) AS
SELECT E.NOMBRE, ID_EQUIPO_CASA, SUM(GOLES_CASA)
FROM PARTIDOS
JOIN EQUIPOS E on E.ID_EQUIPO = PARTIDOS.ID_EQUIPO_CASA
GROUP BY ID_EQUIPO_CASA, NOMBRE
UNION
SELECT E.NOMBRE, ID_EQUIPO_FUERA, SUM(GOLES_FUERA)
FROM PARTIDOS
JOIN EQUIPOS E on E.ID_EQUIPO = PARTIDOS.ID_EQUIPO_FUERA
GROUP BY ID_EQUIPO_FUERA, NOMBRE;



SELECT e.NOMBRE
FROM VGOLES vg
JOIN EQUIPOS e ON (ID_EQUIPO)
