--EJERCICIO 1
SELECT NOMBRE, APELLIDO1, APELLIDO2 FROM ALUMNOS WHERE EDAD < 25;
--EJERCICIO 2
SELECT APELLIDO1 || ' ' || APELLIDO2 || ', ' || NOMBRE FROM ALUMNOS WHERE EDAD < 25;
--EJERCICIO 3
SELECT NOMBRE, APELLIDO1, APELLIDO2 FROM ALUMNOS WHERE TELEFONO IS NULL;
--EJERCICIO 4
SELECT NOMBRE, APELLIDO1, APELLIDO2 FROM ALUMNOS WHERE APELLIDO1 = 'Sánchez' AND APELLIDO2 = 'Sánchez';
--EJERCICIO 5
SELECT NOMBRE, APELLIDO1, APELLIDO2 FROM ALUMNOS WHERE APELLIDO1 = APELLIDO2;
--EJERCICIO 6
SELECT NOMBRE, APELLIDO1, APELLIDO2 FROM ALUMNOS WHERE TELEFONO LIKE '6%' OR TELEFONO LIKE '7%';
--EJERCICIO 7
SELECT NOMBRE, APELLIDO1, APELLIDO2 FROM ALUMNOS WHERE TELEFONO LIKE '%5%5%_';
--EJERCICIO 8
SELECT NOMBRE, APELLIDO1, APELLIDO2 FROM ALUMNOS WHERE TELEFONO LIKE '%5%5%_' AND EDAD > 50;
--EJERCICIO 9
SELECT NOMBRE, APELLIDO1, APELLIDO2 FROM ALUMNOS WHERE ALUMNOS.DIRECCION LIKE 'c Mayor %_' OR DIRECCION LIKE 'C Mayor %_' OR DIRECCION LIKE 'C mayor %_';
--EJERCICIO 10
SELECT NOMBRE, APELLIDO1, APELLIDO2 FROM ALUMNOS WHERE EDAD IN(20, 35, 45);
--EJERCICIO 11
SELECT NOMBRE, APELLIDO1, APELLIDO2 FROM ALUMNOS WHERE APELLIDO1 LIKE 'C%' OR APELLIDO1 LIKE 'H%' OR APELLIDO1 LIKE 'S%';
--EJERCICIO 12
SELECT NOMBRE, APELLIDO1, APELLIDO2, EDAD, EDAD+10 FROM ALUMNOS;
--EJERCICIO 13
SELECT NOMBRE, APELLIDO1, APELLIDO2 FROM ALUMNOS WHERE APELLIDO1 BETWEEN 'M' AND 'U';
--EJERCICIO 14
DELETE FROM ALUMNOS WHERE TELEFONO IS NULL;
ROLLBACK;
--EJERCICIO 15
ALTER TABLE ALUMNOS ADD email VARCHAR2(50);
UPDATE ALUMNOS set email = (NOMBRE||APELLIDO1||'@academiabosco.es') WHERE EMAIL IS NULL;
SELECT EMAIL FROM ALUMNOS;

--EJERCICIO 16
ALTER TABLE ALUMNOS ADD CONSTRAINT alumnos_ck1 CHECK ( TELEFONO ='9%' OR TELEFONO = '6%' OR TELEFONO ='7%' );
SELECT NOMBRE, APELLIDO1, APELLIDO2, EDAD, TELEFONO FROM ALUMNOS;