CREATE USER padremadre IDENTIFIED BY "Herrera2024_" DEFAULT TABLESPACE DATA QUOTA 50M ON DATA ;
GRANT CONNECT, RESOURCE, CREATE VIEW, CREATE MATERIALIZED VIEW TO padremadre;


create table padremadre.personas(
  n_persona number(4) constraint personas_pk primary key,
  nombre varchar2(50) constraint personas_uk1 unique
  					 constraint personas_nn1 not null,
  n_padre number(4) constraint personas_fk1 references padremadre.personas,
  n_madre number(4) constraint personas_fk2 references padremadre.personas,
  sexo char(1) default 'M' 
    constraint personas_ck1 check(sexo='H' OR sexo='M'),
  constraint personas_ck2 
    check(n_padre!=n_madre)
);


INSERT INTO PADREMADRE.PERSONAS (N_PERSONA, NOMBRE, N_PADRE, N_MADRE, SEXO) VALUES (1, 'Ángel', null, null, 'H');
INSERT INTO PADREMADRE.PERSONAS (N_PERSONA, NOMBRE, N_PADRE, N_MADRE, SEXO) VALUES (2, 'María', null, null, 'M');
INSERT INTO PADREMADRE.PERSONAS (N_PERSONA, NOMBRE, N_PADRE, N_MADRE, SEXO) VALUES (3, 'Pedro', null, null, 'H');
INSERT INTO PADREMADRE.PERSONAS (N_PERSONA, NOMBRE, N_PADRE, N_MADRE, SEXO) VALUES (4, 'Luisa', null, null, 'M');
INSERT INTO PADREMADRE.PERSONAS (N_PERSONA, NOMBRE, N_PADRE, N_MADRE, SEXO) VALUES (5, 'Ignacio', null, null, 'H');
INSERT INTO PADREMADRE.PERSONAS (N_PERSONA, NOMBRE, N_PADRE, N_MADRE, SEXO) VALUES (6, 'Javier', null, null, 'H');
INSERT INTO PADREMADRE.PERSONAS (N_PERSONA, NOMBRE, N_PADRE, N_MADRE, SEXO) VALUES (7, 'Lucía', null, null, 'M');
INSERT INTO PADREMADRE.PERSONAS (N_PERSONA, NOMBRE, N_PADRE, N_MADRE, SEXO) VALUES (8, 'Francisco', 1, 2, 'H');
INSERT INTO PADREMADRE.PERSONAS (N_PERSONA, NOMBRE, N_PADRE, N_MADRE, SEXO) VALUES (9, 'Leonisa', 1, 2, 'M');
INSERT INTO PADREMADRE.PERSONAS (N_PERSONA, NOMBRE, N_PADRE, N_MADRE, SEXO) VALUES (10, 'Carmen', 1, 2, 'M');
INSERT INTO PADREMADRE.PERSONAS (N_PERSONA, NOMBRE, N_PADRE, N_MADRE, SEXO) VALUES (11, 'Noemí', 3, 2, 'M');
INSERT INTO PADREMADRE.PERSONAS (N_PERSONA, NOMBRE, N_PADRE, N_MADRE, SEXO) VALUES (12, 'Miranda', 3, 2, 'M');
INSERT INTO PADREMADRE.PERSONAS (N_PERSONA, NOMBRE, N_PADRE, N_MADRE, SEXO) VALUES (13, 'Julián', 6, 7, 'H');
INSERT INTO PADREMADRE.PERSONAS (N_PERSONA, NOMBRE, N_PADRE, N_MADRE, SEXO) VALUES (14, 'Guillermo', 6, 7, 'H');
INSERT INTO PADREMADRE.PERSONAS (N_PERSONA, NOMBRE, N_PADRE, N_MADRE, SEXO) VALUES (15, 'Teresa', 5, 7, 'M');
INSERT INTO PADREMADRE.PERSONAS (N_PERSONA, NOMBRE, N_PADRE, N_MADRE, SEXO) VALUES (16, 'Rodrigo', 5, 7, 'H');
INSERT INTO PADREMADRE.PERSONAS (N_PERSONA, NOMBRE, N_PADRE, N_MADRE, SEXO) VALUES (17, 'Maite', 13, 9, 'M');
INSERT INTO PADREMADRE.PERSONAS (N_PERSONA, NOMBRE, N_PADRE, N_MADRE, SEXO) VALUES (18, 'Pablo', 13, 9, 'H');
INSERT INTO PADREMADRE.PERSONAS (N_PERSONA, NOMBRE, N_PADRE, N_MADRE, SEXO) VALUES (19, 'Zacarías', 14, 10, 'H');
INSERT INTO PADREMADRE.PERSONAS (N_PERSONA, NOMBRE, N_PADRE, N_MADRE, SEXO) VALUES (20, 'Luciano', null, null, 'H');
INSERT INTO PADREMADRE.PERSONAS (N_PERSONA, NOMBRE, N_PADRE, N_MADRE, SEXO) VALUES (21, 'Estela', null, null, 'M');
INSERT INTO PADREMADRE.PERSONAS (N_PERSONA, NOMBRE, N_PADRE, N_MADRE, SEXO) VALUES (22, 'Petronila', null, null, 'M');
INSERT INTO PADREMADRE.PERSONAS (N_PERSONA, NOMBRE, N_PADRE, N_MADRE, SEXO) VALUES (23, 'Carla', null, null, 'M');
INSERT INTO PADREMADRE.PERSONAS (N_PERSONA, NOMBRE, N_PADRE, N_MADRE, SEXO) VALUES (24, 'Eva', null, null, 'M');
INSERT INTO PADREMADRE.PERSONAS (N_PERSONA, NOMBRE, N_PADRE, N_MADRE, SEXO) VALUES (25, 'Mariano', null, null, 'H');
INSERT INTO PADREMADRE.PERSONAS (N_PERSONA, NOMBRE, N_PADRE, N_MADRE, SEXO) VALUES (26, 'Juanjo', null, null, 'H');
INSERT INTO PADREMADRE.PERSONAS (N_PERSONA, NOMBRE, N_PADRE, N_MADRE, SEXO) VALUES (27, 'Esteban', null, null, 'H');
INSERT INTO PADREMADRE.PERSONAS (N_PERSONA, NOMBRE, N_PADRE, N_MADRE, SEXO) VALUES (28, 'Martín', 20, 21, 'H');
INSERT INTO PADREMADRE.PERSONAS (N_PERSONA, NOMBRE, N_PADRE, N_MADRE, SEXO) VALUES (29, 'Miguel', null, null, 'H');
INSERT INTO PADREMADRE.PERSONAS (N_PERSONA, NOMBRE, N_PADRE, N_MADRE, SEXO) VALUES (30, 'Beto', null, null, 'H');
INSERT INTO PADREMADRE.PERSONAS (N_PERSONA, NOMBRE, N_PADRE, N_MADRE, SEXO) VALUES (31, 'Roberto', 30, 22, 'H');
INSERT INTO PADREMADRE.PERSONAS (N_PERSONA, NOMBRE, N_PADRE, N_MADRE, SEXO) VALUES (32, 'Jeremías', 29, 22, 'H');
INSERT INTO PADREMADRE.PERSONAS (N_PERSONA, NOMBRE, N_PADRE, N_MADRE, SEXO) VALUES (33, 'Matías', 29, 22, 'H');
INSERT INTO PADREMADRE.PERSONAS (N_PERSONA, NOMBRE, N_PADRE, N_MADRE, SEXO) VALUES (34, 'Alfonso', null, 22, 'H');
INSERT INTO PADREMADRE.PERSONAS (N_PERSONA, NOMBRE, N_PADRE, N_MADRE, SEXO) VALUES (35, 'Carlos', 25, 24, 'H');
INSERT INTO PADREMADRE.PERSONAS (N_PERSONA, NOMBRE, N_PADRE, N_MADRE, SEXO) VALUES (36, 'Conchita', 25, 24, 'M');
INSERT INTO PADREMADRE.PERSONAS (N_PERSONA, NOMBRE, N_PADRE, N_MADRE, SEXO) VALUES (37, 'David', 25, 24, 'H');
INSERT INTO PADREMADRE.PERSONAS (N_PERSONA, NOMBRE, N_PADRE, N_MADRE, SEXO) VALUES (38, 'Mercedes', 25, 24, 'M');
INSERT INTO PADREMADRE.PERSONAS (N_PERSONA, NOMBRE, N_PADRE, N_MADRE, SEXO) VALUES (39, 'Ricardo', 25, 24, 'H');
INSERT INTO PADREMADRE.PERSONAS (N_PERSONA, NOMBRE, N_PADRE, N_MADRE, SEXO) VALUES (40, 'Adela', 20, 22, 'M');
INSERT INTO PADREMADRE.PERSONAS (N_PERSONA, NOMBRE, N_PADRE, N_MADRE, SEXO) VALUES (41, 'Jaime', 26, 23, 'H');
INSERT INTO PADREMADRE.PERSONAS (N_PERSONA, NOMBRE, N_PADRE, N_MADRE, SEXO) VALUES (42, 'Petra', 26, 23, 'M');
INSERT INTO PADREMADRE.PERSONAS (N_PERSONA, NOMBRE, N_PADRE, N_MADRE, SEXO) VALUES (43, 'Manuela', 41, 36, 'M');
INSERT INTO PADREMADRE.PERSONAS (N_PERSONA, NOMBRE, N_PADRE, N_MADRE, SEXO) VALUES (44, 'Sara', 41, 36, 'M');
INSERT INTO PADREMADRE.PERSONAS (N_PERSONA, NOMBRE, N_PADRE, N_MADRE, SEXO) VALUES (45, 'Felix', 31, 38, 'H');
INSERT INTO PADREMADRE.PERSONAS (N_PERSONA, NOMBRE, N_PADRE, N_MADRE, SEXO) VALUES (46, 'Sandra', 31, 38, 'M');
INSERT INTO PADREMADRE.PERSONAS (N_PERSONA, NOMBRE, N_PADRE, N_MADRE, SEXO) VALUES (47, 'Antonio', 45, 46, 'H');
INSERT INTO PADREMADRE.PERSONAS (N_PERSONA, NOMBRE, N_PADRE, N_MADRE, SEXO) VALUES (48, 'Cristina', 45, 46, 'M');
INSERT INTO PADREMADRE.PERSONAS (N_PERSONA, NOMBRE, N_PADRE, N_MADRE, SEXO) VALUES (49, 'Pura', null, null, 'M');
INSERT INTO PADREMADRE.PERSONAS (N_PERSONA, NOMBRE, N_PADRE, N_MADRE, SEXO) VALUES (50, 'Santiago', null, null, 'H');
INSERT INTO PADREMADRE.PERSONAS (N_PERSONA, NOMBRE, N_PADRE, N_MADRE, SEXO) VALUES (51, 'Gemma', null, null, 'M');
INSERT INTO PADREMADRE.PERSONAS (N_PERSONA, NOMBRE, N_PADRE, N_MADRE, SEXO) VALUES (52, 'Manuel', null, null, 'H');
INSERT INTO PADREMADRE.PERSONAS (N_PERSONA, NOMBRE, N_PADRE, N_MADRE, SEXO) VALUES (53, 'Gerardo', 50, 49, 'H');
INSERT INTO PADREMADRE.PERSONAS (N_PERSONA, NOMBRE, N_PADRE, N_MADRE, SEXO) VALUES (54, 'Juan', 50, 49, 'H');
INSERT INTO PADREMADRE.PERSONAS (N_PERSONA, NOMBRE, N_PADRE, N_MADRE, SEXO) VALUES (55, 'Sofía', 52, 51, 'M');
INSERT INTO PADREMADRE.PERSONAS (N_PERSONA, NOMBRE, N_PADRE, N_MADRE, SEXO) VALUES (56, 'Jazmín', 52, 51, 'M');
INSERT INTO PADREMADRE.PERSONAS (N_PERSONA, NOMBRE, N_PADRE, N_MADRE, SEXO) VALUES (57, 'Rubén', 52, 51, 'M');
INSERT INTO PADREMADRE.PERSONAS (N_PERSONA, NOMBRE, N_PADRE, N_MADRE, SEXO) VALUES (58, 'Felipe', 54, 56, 'H');
INSERT INTO PADREMADRE.PERSONAS (N_PERSONA, NOMBRE, N_PADRE, N_MADRE, SEXO) VALUES (59, 'Dionisio', null, null, 'H');
INSERT INTO PADREMADRE.PERSONAS (N_PERSONA, NOMBRE, N_PADRE, N_MADRE, SEXO) VALUES (60, 'Julia', null, null, 'M');
INSERT INTO PADREMADRE.PERSONAS (N_PERSONA, NOMBRE, N_PADRE, N_MADRE, SEXO) VALUES (61, 'Blanca', 59, 60, 'M');
INSERT INTO PADREMADRE.PERSONAS (N_PERSONA, NOMBRE, N_PADRE, N_MADRE, SEXO) VALUES (62, 'Rosa', 59, 60, 'M');
INSERT INTO PADREMADRE.PERSONAS (N_PERSONA, NOMBRE, N_PADRE, N_MADRE, SEXO) VALUES (63, 'Paloma', 59, 60, 'M');
INSERT INTO PADREMADRE.PERSONAS (N_PERSONA, NOMBRE, N_PADRE, N_MADRE, SEXO) VALUES (64, 'Leandro', 53, 61, 'H');
INSERT INTO PADREMADRE.PERSONAS (N_PERSONA, NOMBRE, N_PADRE, N_MADRE, SEXO) VALUES (65, 'Raul', 53, 61, 'H');
INSERT INTO PADREMADRE.PERSONAS (N_PERSONA, NOMBRE, N_PADRE, N_MADRE, SEXO) VALUES (66, 'Beatriz', 53, 61, 'M');
INSERT INTO PADREMADRE.PERSONAS (N_PERSONA, NOMBRE, N_PADRE, N_MADRE, SEXO) VALUES (67, 'Rebeca', 53, 61, 'M');
INSERT INTO PADREMADRE.PERSONAS (N_PERSONA, NOMBRE, N_PADRE, N_MADRE, SEXO) VALUES (68, 'Paulino', 64, 55, 'H');
INSERT INTO PADREMADRE.PERSONAS (N_PERSONA, NOMBRE, N_PADRE, N_MADRE, SEXO) VALUES (69, 'César', null, 63, 'H');
COMMIT;