--EJERCICIO1
SELECT NOMBRE
FROM PERSONAS
WHERE n_padre is null AND n_madre is null;
--EJERCICIO2
SELECT h.NOMBRE AS HIJO, m.NOMBRE AS MADRE, p.NOMBRE AS PADRE
FROM PERSONAS h
JOIN PERSONAS m ON(h.N_MADRE=m.N_PERSONA)
JOIN PERSONAS p ON(h.N_PADRE=p.N_PERSONA);
--EJERCICIO3
SELECT h.NOMBRE AS HIJO, m.NOMBRE AS MADRE, p.NOMBRE AS PADRE
FROM PERSONAS h
LEFT OUTER JOIN PERSONAS m ON(h.N_MADRE=m.N_PERSONA)
LEFT OUTER JOIN PERSONAS p ON(h.N_PADRE=p.N_PERSONA);
--EJERCICIO4
SELECT m.NOMBRE AS MADRE, p.NOMBRE AS PADRE, COUNT(*) AS NÚMERO_DE_HIJOS
FROM PERSONAS h
LEFT OUTER JOIN PERSONAS m ON(h.N_MADRE=m.N_PERSONA)
LEFT OUTER JOIN PERSONAS p ON(h.N_PADRE=p.N_PERSONA)
WHERE m.NOMBRE IS NOT NULL AND p.NOMBRE IS NOT NULL
GROUP BY (m.NOMBRE, p.NOMBRE)
ORDER BY NÚMERO_DE_HIJOS DESC , p.NOMBRE, m.NOMBRE;
--EJERCICIO5
SELECT m.NOMBRE AS MADRE, COUNT(h.NOMBRE) AS NÚMERO_DE_HIJOS
FROM PERSONAS h
JOIN PERSONAS m ON(h.N_MADRE=m.N_PERSONA)
WHERE m.NOMBRE IS NOT NULL
HAVING COUNT(h.NOMBRE) = 2
GROUP BY (m.NOMBRE)
ORDER BY NÚMERO_DE_HIJOS DESC , m.NOMBRE;
--EJERCICO6
SELECT h.NOMBRE as Hijo, p.NOMBRE as Padre
FROM PERSONAS h
JOIN PERSONAS p ON(h.N_PADRE = p.N_PERSONA)
WHERE SUBSTR(h.NOMBRE,1,1) = SUBSTR(P.NOMBRE,1,1);
--EJERCICIO7
SELECT m.NOMBRE
FROM PERSONAS h
JOIN PERSONAS m ON (h.N_MADRE=m.N_PERSONA)
JOIN PERSONAS p ON (h.N_PADRE=p.N_PERSONA)
HAVING COUNT(DISTINCT p.NOMBRE) >=2
GROUP BY (m.NOMBRE)
ORDER BY m.NOMBRE;

--EJERCICIO8
SELECT m2.NOMBRE
FROM PERSONAS h
JOIN PERSONAS m ON(h.N_MADRE = m.N_PERSONA)
JOIN PERSONAS m2 ON(m.N_MADRE = m2.N_PERSONA)
GROUP BY (m2.NOMBRE);

--EJERCICIO9
SELECT p.NOMBRE
FROM PERSONAS h
CROSS JOIN PERSONAS p
WHERE 
GROUP BY (p.NOMBRE)
