--EJERCICIO1
SELECT l.NOMBRE AS LOCALIDAD, l.POBLACION, p.NOMBRE AS PROVINVIA
FROM LOCALIDADES l
JOIN PROVINCIAS p USING (N_PROVINCIA);

--EJERCICIO2
SELECT p.NOMBRE AS PROVINCIA, l.NOMBRE AS CAPITAL
FROM PROVINCIAS p
JOIN LOCALIDADES l ON p.ID_CAPITAL = l.ID_LOCALIDAD;

--EJERCICIO3
SELECT l.NOMBRE AS LOCALIDAD, p.NOMBRE AS PROVINCIA, c.NOMBRE AS NOMBRE
FROM LOCALIDADES l
JOIN PROVINCIAS p USING (N_PROVINCIA)
JOIN COMUNIDADES c USING (ID_COMUNIDAD);

--EJERCICIO4
--cAMBIAR
SELECT l.NOMBRE AS LOCALIDAD, p.NOMBRE AS PROVINCIA, c.NOMBRE AS NOMBRE, l2.NOMBRE AS CAPITAL
FROM LOCALIDADES l
JOIN PROVINCIAS p USING (N_PROVINCIA)
JOIN COMUNIDADES c USING (ID_COMUNIDAD)
JOIN LOCALIDADES l2 USING (ID_LOCALIDAD);
