SELECT N_ALMACEN, TIPO,MODELO
FROM ALMACENES a
JOIN EXISTENCIAS e USING(N_ALMACEN)
JOIN PIEZAS p USING(TIPO, MODELO)
WHERE CANTIDAD>2000 AND CANTIDAD<3000;

--EJERCICIO2
SELECT TIPO, MODELO, PRECIO_VENTA, N_ALMACEN, CANTIDAD
FROM PIEZAS
JOIN EXISTENCIAS USING (TIPO, MODELO)
JOIN ALMACENES USING (N_ALMACEN);

--EJERCICIO3
SELECT e.NOMBRE, LOCALIDAD, TIPO, MODELO, PRECIO_COMPRA
FROM EMPRESAS e
JOIN SUMINISTROS s USING (CIF);

--EJERCICIO4
SELECT e.NOMBRE, LOCALIDAD, TIPO, MODELO, PRECIO_COMPRA
FROM EMPRESAS e
JOIN SUMINISTROS s USING (CIF)
JOIN PIEZAS p USING (TIPO, MODELO)
WHERE PRECIO_COMPRA>PRECIO_VENTA;

--EJERCICIO5
SELECT p.N_PEDIDO, e.NOMBRE, TO_CHAR(p.FECHA, 'fmDay dd "de" Month "del año" yyyy')
FROM PEDIDOS p
JOIN EMPRESAS e USING (CIF);

--EJERCICIO6
SELECT p.N_PEDIDO, e.NOMBRE, TO_CHAR(p.FECHA, 'fm"Trimestre "Q Dy dd"#"mm"#"yyyy')
FROM PEDIDOS p
JOIN EMPRESAS e USING (CIF);

--EJERCICIO7
SELECT e.NOMBRE, e.TELEFONO
FROM EMPRESAS e
WHERE TELEFONO LIKE '%1'
   OR TELEFONO LIKE '%3'
   OR TELEFONO LIKE '%5'
   OR TELEFONO LIKE '%6';

--EJERCICIO8
SELECT NOMBRE, TELEFONO
FROM EMPRESAS
WHERE MOD(SUBSTR(TELEFONO,3,1),2)=0;

--EJERCICIO9
SELECT e1.PROVINCIA
FROM EMPRESAS e1
WHERE e1.PROVINCIA IS NOT NULL
GROUP BY PROVINCIA;

--EJERCICIO10
SELECT TIPO, MODELO, PRECIO_VENTA, ROUND(
    (((PRECIO_VENTA*21)/100) +PRECIO_VENTA),
    3) AS PRECIO_CON_IVA
FROM PIEZAS;
--EJERCICIO11
SELECT DESCRIPCION, lp.CANTIDAD, TIPO, lp.MODELO, PRECIO_VENTA,
        CASE N_ALMACEN
        WHEN 1 THEN 'Almacen 1'
        WHEN 2 THEN 'Almacen 2'
        WHEN 3 THEN 'Almacen 3'
        END
            AS ALMACEN

FROM ALMACENES
JOIN EXISTENCIAS USING (N_ALMACEN)
JOIN PIEZAS USING (TIPO)
JOIN LINEAS_PEDIDO lp USING (TIPO)
ORDER BY N_ALMACEN, TIPO, MODELO;