
CREATE USER redsocial IDENTIFIED BY "Herrera2024_" DEFAULT TABLESPACE DATA QUOTA 50M ON DATA ;
GRANT CONNECT, RESOURCE, CREATE VIEW, CREATE MATERIALIZED VIEW TO redsocial;


CREATE TABLE redsocial.usuarios(
	id_usu NUMBER(10) 		CONSTRAINT usuarios_pk PRIMARY KEY,
	usuario VARCHAR2(15) 	CONSTRAINT usuarios_nn1 NOT NULL
								CONSTRAINT usuarios_uk1 UNIQUE
								CONSTRAINT usuarios_ck1 
									CHECK(REGEXP_LIKE(usuario,'^[a-z]+$')),
	contra VARCHAR2(30) 	CONSTRAINT usuarios_nn2 NOT NULL
								CONSTRAINT usuarios_ck2
									CHECK(LENGTH(contra)>4),
	email VARCHAR2(50) 		CONSTRAINT usuarios_nn3 NOT NULL
								CONSTRAINT usuarios_uk3 UNIQUE
								CONSTRAINT usuarios_ck3
									CHECK (REGEXP_LIKE(email,
			'^[a-zA-Z0-9\-_]+(\.[a-zA-Z0-9\-_]+)*@[a-zA-Z0-9\-_]+(\.[a-zA-Z0-9\-_]+)*\.[a-z]{2,3}$')),
	nombre VARCHAR2(35)	CONSTRAINT usuarios_nn4 NOT NULL,
	apellido1 VARCHAR2(35)	CONSTRAINT usuarios_nn5 NOT NULL,
	apellido2 VARCHAR2(35),
	fecha_nac DATE
);

CREATE TABLE redsocial.amigos(
	id_usu NUMBER(10) 		CONSTRAINT amigos_fk1 REFERENCES redsocial.usuarios ON DELETE CASCADE,
	id_amigo NUMBER(10)	CONSTRAINT amigos_fk2 REFERENCES redsocial.usuarios ON DELETE CASCADE,
	CONSTRAINT amigos_pk 	PRIMARY KEY(id_usu,id_amigo)
);

CREATE TABLE redsocial.mensajes(
	id_usu NUMBER(10) ,
	id_amigo NUMBER(10),
	fecha TIMESTAMP,
	texto VARCHAR2(250) CONSTRAINT mensajes_nn NOT NULL,
	CONSTRAINT mensajes_pk 	PRIMARY KEY(id_usu,id_amigo, fecha),
	CONSTRAINT mensajes_fk1 FOREIGN KEY(id_usu,id_amigo) REFERENCES redsocial.amigos
);

INSERT INTO REDSOCIAL.USUARIOS (ID_USU, USUARIO, CONTRA, EMAIL, NOMBRE, APELLIDO1, APELLIDO2, FECHA_NAC) VALUES (1, 'miguel', 'calasparra', 'miguel@gmail.com', 'Miguel', 'Rodriguez', 'Crespo', DATE '1981-03-12');
INSERT INTO REDSOCIAL.USUARIOS (ID_USU, USUARIO, CONTRA, EMAIL, NOMBRE, APELLIDO1, APELLIDO2, FECHA_NAC) VALUES (2, 'andrea', 'p23r561a', 'andrea.marcos@tdisg.net', 'Andrea', 'Marcos', 'Sierra', DATE '1979-06-06');
INSERT INTO REDSOCIAL.USUARIOS (ID_USU, USUARIO, CONTRA, EMAIL, NOMBRE, APELLIDO1, APELLIDO2, FECHA_NAC) VALUES (3, 'samuel', 'samusamu', 'samusamu@gmail.com', 'Samuel', 'Valdepeñas', 'Orize', DATE '1982-07-06');
INSERT INTO REDSOCIAL.USUARIOS (ID_USU, USUARIO, CONTRA, EMAIL, NOMBRE, APELLIDO1, APELLIDO2, FECHA_NAC) VALUES (4, 'paula', 'paula4321', 'paula.zabaleta@tdisg.net', 'Paula', 'Zabaleta', 'Romero', DATE '1983-08-17');
INSERT INTO REDSOCIAL.USUARIOS (ID_USU, USUARIO, CONTRA, EMAIL, NOMBRE, APELLIDO1, APELLIDO2, FECHA_NAC) VALUES (5, 'ricardo', 'uert"13LKa', 'richar@polmatec.net', 'Ricardo', 'Crespo', 'Santo Angel', DATE '1980-09-06');
INSERT INTO REDSOCIAL.USUARIOS (ID_USU, USUARIO, CONTRA, EMAIL, NOMBRE, APELLIDO1, APELLIDO2, FECHA_NAC) VALUES (6, 'elena', '123456', 'elena1981@yahoo.es', 'Elena', 'Castro', 'Valdeajos', DATE '1982-07-09');
INSERT INTO REDSOCIAL.USUARIOS (ID_USU, USUARIO, CONTRA, EMAIL, NOMBRE, APELLIDO1, APELLIDO2, FECHA_NAC) VALUES (7, 'victor', '54321', 'victorarranz@gmail.com', 'Victor', 'Arranz', 'Gonsálvez', DATE '1982-04-07');
INSERT INTO REDSOCIAL.USUARIOS (ID_USU, USUARIO, CONTRA, EMAIL, NOMBRE, APELLIDO1, APELLIDO2, FECHA_NAC) VALUES (8, 'ana', 'soyana', 'anaanaana@hotmail.com', 'Ana', 'Andrés', 'Nieto', DATE '1981-12-06');
INSERT INTO REDSOCIAL.USUARIOS (ID_USU, USUARIO, CONTRA, EMAIL, NOMBRE, APELLIDO1, APELLIDO2, FECHA_NAC) VALUES (9, 'rosa', '"caserta"1', 'rosaandres@hotmail.com', 'Rosa', 'Andrés', 'Nieto', DATE '1981-12-06');
INSERT INTO REDSOCIAL.USUARIOS (ID_USU, USUARIO, CONTRA, EMAIL, NOMBRE, APELLIDO1, APELLIDO2, FECHA_NAC) VALUES (10, 'gabriel', 'Z1b0r2==', 'g12345@outlook.com', 'Gabriel', 'Soto', 'Sierra', DATE '1981-12-06');
INSERT INTO REDSOCIAL.USUARIOS (ID_USU, USUARIO, CONTRA, EMAIL, NOMBRE, APELLIDO1, APELLIDO2, FECHA_NAC) VALUES (11, 'nazario', 'nazari1', 'nazanpum@apple.com', 'Nazario', 'Sánchez', 'Ceinos', DATE '1979-11-07');
INSERT INTO REDSOCIAL.USUARIOS (ID_USU, USUARIO, CONTRA, EMAIL, NOMBRE, APELLIDO1, APELLIDO2, FECHA_NAC) VALUES (12, 'teresa', 'tteresat', 'tteresat@apple.com', 'Teresa', 'Sánchez', 'Ceinos', DATE '1983-01-08');
INSERT INTO REDSOCIAL.USUARIOS (ID_USU, USUARIO, CONTRA, EMAIL, NOMBRE, APELLIDO1, APELLIDO2, FECHA_NAC) VALUES (13, 'jordi', 'A@df167', 'jordisaura@galamp.net', 'Jordi', 'Saura', 'Gil', DATE '1984-08-06');
INSERT INTO REDSOCIAL.USUARIOS (ID_USU, USUARIO, CONTRA, EMAIL, NOMBRE, APELLIDO1, APELLIDO2, FECHA_NAC) VALUES (14, 'ursula', 'ursulina', 'admin@ursula.es', 'Ursula', 'Valle', 'Sánchez', DATE '1991-12-01');
INSERT INTO REDSOCIAL.USUARIOS (ID_USU, USUARIO, CONTRA, EMAIL, NOMBRE, APELLIDO1, APELLIDO2, FECHA_NAC) VALUES (15, 'asier', 'Jsd87623jdf^j', 'asierheredia@kabriz.es', 'Asier', 'Heredia', 'García', DATE '1990-09-05');
INSERT INTO REDSOCIAL.USUARIOS (ID_USU, USUARIO, CONTRA, EMAIL, NOMBRE, APELLIDO1, APELLIDO2, FECHA_NAC) VALUES (16, 'izan', 'e=mc2', 'cascorrodelpueblo@kabriz.net', 'Izan', 'Heredia', 'García', DATE '1991-11-07');
INSERT INTO REDSOCIAL.USUARIOS (ID_USU, USUARIO, CONTRA, EMAIL, NOMBRE, APELLIDO1, APELLIDO2, FECHA_NAC) VALUES (17, 'pedro', 'kazabarskks', 'pedrito@gmail.com', 'Pedro', 'Sánchez', 'Román', DATE '1970-08-01');
INSERT INTO REDSOCIAL.USUARIOS (ID_USU, USUARIO, CONTRA, EMAIL, NOMBRE, APELLIDO1, APELLIDO2, FECHA_NAC) VALUES (18, 'jaime', 'jaim1897sanchez', 'jaime@terra.es', 'Jaime', 'Sánchez', 'García', DATE '1996-09-01');
INSERT INTO REDSOCIAL.USUARIOS (ID_USU, USUARIO, CONTRA, EMAIL, NOMBRE, APELLIDO1, APELLIDO2, FECHA_NAC) VALUES (19, 'ruben', 'rubyguay', 'rubyguay@terra.es', 'Rubén', 'Sánchez', 'García', DATE '1999-08-05');
INSERT INTO REDSOCIAL.USUARIOS (ID_USU, USUARIO, CONTRA, EMAIL, NOMBRE, APELLIDO1, APELLIDO2, FECHA_NAC) VALUES (20, 'gorka', '22*3=66Perfect!', 'gorkkkka@euskaltel.net', 'Gorka', 'Etxebesti', 'Ruiz', DATE '1976-12-15');
INSERT INTO REDSOCIAL.USUARIOS (ID_USU, USUARIO, CONTRA, EMAIL, NOMBRE, APELLIDO1, APELLIDO2, FECHA_NAC) VALUES (21, 'lope', 'R3v0luc10n!', 'R3v0luc10n@euskatel.net', 'Lope', 'Arias', 'González', DATE '1976-12-15');
INSERT INTO REDSOCIAL.USUARIOS (ID_USU, USUARIO, CONTRA, EMAIL, NOMBRE, APELLIDO1, APELLIDO2, FECHA_NAC) VALUES (22, 'leire', 'leirre', 'leire@mo1980.com', 'Leire', 'Arias', 'González', DATE '1981-02-08');
INSERT INTO REDSOCIAL.USUARIOS (ID_USU, USUARIO, CONTRA, EMAIL, NOMBRE, APELLIDO1, APELLIDO2, FECHA_NAC) VALUES (23, 'millan', '!!!gomez!!!', 'gomezmillan@outlook.com', 'Millan', 'Gómez', 'Luján', DATE '1988-12-29');
INSERT INTO REDSOCIAL.USUARIOS (ID_USU, USUARIO, CONTRA, EMAIL, NOMBRE, APELLIDO1, APELLIDO2, FECHA_NAC) VALUES (24, 'xavi', 'xavier--serrat', 'xavierserrat@outlook.com', 'Xavier', 'Serrat', 'Estadella', DATE '1991-01-12');
INSERT INTO REDSOCIAL.USUARIOS (ID_USU, USUARIO, CONTRA, EMAIL, NOMBRE, APELLIDO1, APELLIDO2, FECHA_NAC) VALUES (25, 'lluis', 'Al23R/1"3G', 'gerente@isdema.es', 'Lluis', 'Serrat', 'Estadella', DATE '1991-01-12');
INSERT INTO REDSOCIAL.USUARIOS (ID_USU, USUARIO, CONTRA, EMAIL, NOMBRE, APELLIDO1, APELLIDO2, FECHA_NAC) VALUES (26, 'jurgen', 'DrEyEr', 'dreyerjurg@microsoft.com', 'Jurgen', 'Dreyer', 'Hepfner', DATE '1968-03-10');
INSERT INTO REDSOCIAL.USUARIOS (ID_USU, USUARIO, CONTRA, EMAIL, NOMBRE, APELLIDO1, APELLIDO2, FECHA_NAC) VALUES (27, 'emma', '|@##~€~€¬¬', 'emma.dep21@asira.es', 'Emma', 'Cabrerizo', 'Lomas', DATE '1962-01-12');
INSERT INTO REDSOCIAL.USUARIOS (ID_USU, USUARIO, CONTRA, EMAIL, NOMBRE, APELLIDO1, APELLIDO2, FECHA_NAC) VALUES (28, 'winston', 'winstontheking', 'winstontheking@hotmail.com', 'Winston', 'Howlett', null, DATE '1999-03-11');
INSERT INTO REDSOCIAL.USUARIOS (ID_USU, USUARIO, CONTRA, EMAIL, NOMBRE, APELLIDO1, APELLIDO2, FECHA_NAC) VALUES (29, 'damian', 'd4m14n', 'evildamian@hotmail.com', 'Damian', 'Cornwall', null, DATE '1998-01-12');
INSERT INTO REDSOCIAL.USUARIOS (ID_USU, USUARIO, CONTRA, EMAIL, NOMBRE, APELLIDO1, APELLIDO2, FECHA_NAC) VALUES (30, 'adlington', 'adlinrose', 'adlingtonrose@outlook.com', 'Adlington', 'Rose', null, DATE '1986-03-11');
INSERT INTO REDSOCIAL.USUARIOS (ID_USU, USUARIO, CONTRA, EMAIL, NOMBRE, APELLIDO1, APELLIDO2, FECHA_NAC) VALUES (31, 'greidy', 'Gr31dy', 'greidy31@apple.com', 'Greidy', 'Manners', null, DATE '1990-01-12');
INSERT INTO REDSOCIAL.USUARIOS (ID_USU, USUARIO, CONTRA, EMAIL, NOMBRE, APELLIDO1, APELLIDO2, FECHA_NAC) VALUES (32, 'sarah', 's4r4h', 'sarahmiles@thecorp.uk.com', 'Sarah', 'Miles', null, DATE '1993-01-10');
INSERT INTO REDSOCIAL.USUARIOS (ID_USU, USUARIO, CONTRA, EMAIL, NOMBRE, APELLIDO1, APELLIDO2, FECHA_NAC) VALUES (33, 'rose', 'rosalexandra', 'rosemiles@thecorp.uk.com', 'Rose', 'Miles', null, DATE '1995-03-12');
INSERT INTO REDSOCIAL.USUARIOS (ID_USU, USUARIO, CONTRA, EMAIL, NOMBRE, APELLIDO1, APELLIDO2, FECHA_NAC) VALUES (34, 'alberta', 'alb-er-ta', 'alberta@thecorp.uk.com', 'Alberta', 'Miles', null, DATE '1996-04-17');
INSERT INTO REDSOCIAL.USUARIOS (ID_USU, USUARIO, CONTRA, EMAIL, NOMBRE, APELLIDO1, APELLIDO2, FECHA_NAC) VALUES (35, 'jorge', '123456', 'a@b.com', 'Jorge', 'Sanchez', null, null);
INSERT INTO REDSOCIAL.USUARIOS (ID_USU, USUARIO, CONTRA, EMAIL, NOMBRE, APELLIDO1, APELLIDO2, FECHA_NAC) VALUES (36, 'mariana', 'e=mc2', 'mariana.san.si@gmail.com', 'Mariana', 'Sansimón', 'Orcada', DATE '2000-03-12');
INSERT INTO REDSOCIAL.USUARIOS (ID_USU, USUARIO, CONTRA, EMAIL, NOMBRE, APELLIDO1, APELLIDO2, FECHA_NAC) VALUES (37, 'lola', 'calasparra', 'lola.san.si@gmail.com', 'Lola', 'Sansimón', 'Orcada', DATE '2001-05-31');
INSERT INTO REDSOCIAL.USUARIOS (ID_USU, USUARIO, CONTRA, EMAIL, NOMBRE, APELLIDO1, APELLIDO2, FECHA_NAC) VALUES (38, 'santos', 'sd67fdhj%Q', 'santos2001@hotmail.com', 'Santos', 'Oyarzábal', 'Bonda', DATE '2005-08-17');


INSERT INTO REDSOCIAL.AMIGOS (ID_USU, ID_AMIGO) VALUES (1, 2);
INSERT INTO REDSOCIAL.AMIGOS (ID_USU, ID_AMIGO) VALUES (1, 3);
INSERT INTO REDSOCIAL.AMIGOS (ID_USU, ID_AMIGO) VALUES (1, 4);
INSERT INTO REDSOCIAL.AMIGOS (ID_USU, ID_AMIGO) VALUES (1, 5);
INSERT INTO REDSOCIAL.AMIGOS (ID_USU, ID_AMIGO) VALUES (1, 14);
INSERT INTO REDSOCIAL.AMIGOS (ID_USU, ID_AMIGO) VALUES (1, 15);
INSERT INTO REDSOCIAL.AMIGOS (ID_USU, ID_AMIGO) VALUES (2, 1);
INSERT INTO REDSOCIAL.AMIGOS (ID_USU, ID_AMIGO) VALUES (2, 3);
INSERT INTO REDSOCIAL.AMIGOS (ID_USU, ID_AMIGO) VALUES (2, 4);
INSERT INTO REDSOCIAL.AMIGOS (ID_USU, ID_AMIGO) VALUES (3, 1);
INSERT INTO REDSOCIAL.AMIGOS (ID_USU, ID_AMIGO) VALUES (3, 2);
INSERT INTO REDSOCIAL.AMIGOS (ID_USU, ID_AMIGO) VALUES (3, 4);
INSERT INTO REDSOCIAL.AMIGOS (ID_USU, ID_AMIGO) VALUES (4, 1);
INSERT INTO REDSOCIAL.AMIGOS (ID_USU, ID_AMIGO) VALUES (4, 2);
INSERT INTO REDSOCIAL.AMIGOS (ID_USU, ID_AMIGO) VALUES (4, 3);
INSERT INTO REDSOCIAL.AMIGOS (ID_USU, ID_AMIGO) VALUES (4, 5);
INSERT INTO REDSOCIAL.AMIGOS (ID_USU, ID_AMIGO) VALUES (5, 1);
INSERT INTO REDSOCIAL.AMIGOS (ID_USU, ID_AMIGO) VALUES (5, 4);
INSERT INTO REDSOCIAL.AMIGOS (ID_USU, ID_AMIGO) VALUES (5, 6);
INSERT INTO REDSOCIAL.AMIGOS (ID_USU, ID_AMIGO) VALUES (5, 8);
INSERT INTO REDSOCIAL.AMIGOS (ID_USU, ID_AMIGO) VALUES (6, 5);
INSERT INTO REDSOCIAL.AMIGOS (ID_USU, ID_AMIGO) VALUES (6, 7);
INSERT INTO REDSOCIAL.AMIGOS (ID_USU, ID_AMIGO) VALUES (6, 8);
INSERT INTO REDSOCIAL.AMIGOS (ID_USU, ID_AMIGO) VALUES (7, 6);
INSERT INTO REDSOCIAL.AMIGOS (ID_USU, ID_AMIGO) VALUES (7, 8);
INSERT INTO REDSOCIAL.AMIGOS (ID_USU, ID_AMIGO) VALUES (8, 5);
INSERT INTO REDSOCIAL.AMIGOS (ID_USU, ID_AMIGO) VALUES (8, 6);
INSERT INTO REDSOCIAL.AMIGOS (ID_USU, ID_AMIGO) VALUES (8, 7);
INSERT INTO REDSOCIAL.AMIGOS (ID_USU, ID_AMIGO) VALUES (8, 9);
INSERT INTO REDSOCIAL.AMIGOS (ID_USU, ID_AMIGO) VALUES (9, 8);
INSERT INTO REDSOCIAL.AMIGOS (ID_USU, ID_AMIGO) VALUES (10, 11);
INSERT INTO REDSOCIAL.AMIGOS (ID_USU, ID_AMIGO) VALUES (10, 12);
INSERT INTO REDSOCIAL.AMIGOS (ID_USU, ID_AMIGO) VALUES (10, 13);
INSERT INTO REDSOCIAL.AMIGOS (ID_USU, ID_AMIGO) VALUES (11, 10);
INSERT INTO REDSOCIAL.AMIGOS (ID_USU, ID_AMIGO) VALUES (11, 12);
INSERT INTO REDSOCIAL.AMIGOS (ID_USU, ID_AMIGO) VALUES (11, 20);
INSERT INTO REDSOCIAL.AMIGOS (ID_USU, ID_AMIGO) VALUES (11, 21);
INSERT INTO REDSOCIAL.AMIGOS (ID_USU, ID_AMIGO) VALUES (12, 10);
INSERT INTO REDSOCIAL.AMIGOS (ID_USU, ID_AMIGO) VALUES (12, 11);
INSERT INTO REDSOCIAL.AMIGOS (ID_USU, ID_AMIGO) VALUES (12, 20);
INSERT INTO REDSOCIAL.AMIGOS (ID_USU, ID_AMIGO) VALUES (13, 10);
INSERT INTO REDSOCIAL.AMIGOS (ID_USU, ID_AMIGO) VALUES (13, 21);
INSERT INTO REDSOCIAL.AMIGOS (ID_USU, ID_AMIGO) VALUES (14, 1);
INSERT INTO REDSOCIAL.AMIGOS (ID_USU, ID_AMIGO) VALUES (14, 15);
INSERT INTO REDSOCIAL.AMIGOS (ID_USU, ID_AMIGO) VALUES (15, 1);
INSERT INTO REDSOCIAL.AMIGOS (ID_USU, ID_AMIGO) VALUES (15, 14);
INSERT INTO REDSOCIAL.AMIGOS (ID_USU, ID_AMIGO) VALUES (15, 16);
INSERT INTO REDSOCIAL.AMIGOS (ID_USU, ID_AMIGO) VALUES (15, 19);
INSERT INTO REDSOCIAL.AMIGOS (ID_USU, ID_AMIGO) VALUES (16, 15);
INSERT INTO REDSOCIAL.AMIGOS (ID_USU, ID_AMIGO) VALUES (16, 17);
INSERT INTO REDSOCIAL.AMIGOS (ID_USU, ID_AMIGO) VALUES (16, 18);
INSERT INTO REDSOCIAL.AMIGOS (ID_USU, ID_AMIGO) VALUES (16, 19);
INSERT INTO REDSOCIAL.AMIGOS (ID_USU, ID_AMIGO) VALUES (17, 16);
INSERT INTO REDSOCIAL.AMIGOS (ID_USU, ID_AMIGO) VALUES (17, 18);
INSERT INTO REDSOCIAL.AMIGOS (ID_USU, ID_AMIGO) VALUES (17, 19);
INSERT INTO REDSOCIAL.AMIGOS (ID_USU, ID_AMIGO) VALUES (18, 16);
INSERT INTO REDSOCIAL.AMIGOS (ID_USU, ID_AMIGO) VALUES (18, 17);
INSERT INTO REDSOCIAL.AMIGOS (ID_USU, ID_AMIGO) VALUES (19, 15);
INSERT INTO REDSOCIAL.AMIGOS (ID_USU, ID_AMIGO) VALUES (19, 16);
INSERT INTO REDSOCIAL.AMIGOS (ID_USU, ID_AMIGO) VALUES (19, 17);
INSERT INTO REDSOCIAL.AMIGOS (ID_USU, ID_AMIGO) VALUES (19, 21);
INSERT INTO REDSOCIAL.AMIGOS (ID_USU, ID_AMIGO) VALUES (20, 11);
INSERT INTO REDSOCIAL.AMIGOS (ID_USU, ID_AMIGO) VALUES (20, 12);
INSERT INTO REDSOCIAL.AMIGOS (ID_USU, ID_AMIGO) VALUES (20, 21);
INSERT INTO REDSOCIAL.AMIGOS (ID_USU, ID_AMIGO) VALUES (21, 11);
INSERT INTO REDSOCIAL.AMIGOS (ID_USU, ID_AMIGO) VALUES (21, 13);
INSERT INTO REDSOCIAL.AMIGOS (ID_USU, ID_AMIGO) VALUES (21, 19);
INSERT INTO REDSOCIAL.AMIGOS (ID_USU, ID_AMIGO) VALUES (21, 20);
INSERT INTO REDSOCIAL.AMIGOS (ID_USU, ID_AMIGO) VALUES (21, 22);
INSERT INTO REDSOCIAL.AMIGOS (ID_USU, ID_AMIGO) VALUES (21, 23);
INSERT INTO REDSOCIAL.AMIGOS (ID_USU, ID_AMIGO) VALUES (22, 21);
INSERT INTO REDSOCIAL.AMIGOS (ID_USU, ID_AMIGO) VALUES (22, 23);
INSERT INTO REDSOCIAL.AMIGOS (ID_USU, ID_AMIGO) VALUES (22, 24);
INSERT INTO REDSOCIAL.AMIGOS (ID_USU, ID_AMIGO) VALUES (23, 21);
INSERT INTO REDSOCIAL.AMIGOS (ID_USU, ID_AMIGO) VALUES (23, 22);
INSERT INTO REDSOCIAL.AMIGOS (ID_USU, ID_AMIGO) VALUES (23, 24);
INSERT INTO REDSOCIAL.AMIGOS (ID_USU, ID_AMIGO) VALUES (24, 22);
INSERT INTO REDSOCIAL.AMIGOS (ID_USU, ID_AMIGO) VALUES (24, 23);
INSERT INTO REDSOCIAL.AMIGOS (ID_USU, ID_AMIGO) VALUES (28, 29);
INSERT INTO REDSOCIAL.AMIGOS (ID_USU, ID_AMIGO) VALUES (28, 30);
INSERT INTO REDSOCIAL.AMIGOS (ID_USU, ID_AMIGO) VALUES (28, 31);
INSERT INTO REDSOCIAL.AMIGOS (ID_USU, ID_AMIGO) VALUES (28, 33);
INSERT INTO REDSOCIAL.AMIGOS (ID_USU, ID_AMIGO) VALUES (29, 28);
INSERT INTO REDSOCIAL.AMIGOS (ID_USU, ID_AMIGO) VALUES (29, 30);
INSERT INTO REDSOCIAL.AMIGOS (ID_USU, ID_AMIGO) VALUES (29, 31);
INSERT INTO REDSOCIAL.AMIGOS (ID_USU, ID_AMIGO) VALUES (29, 32);
INSERT INTO REDSOCIAL.AMIGOS (ID_USU, ID_AMIGO) VALUES (29, 33);
INSERT INTO REDSOCIAL.AMIGOS (ID_USU, ID_AMIGO) VALUES (29, 34);
INSERT INTO REDSOCIAL.AMIGOS (ID_USU, ID_AMIGO) VALUES (30, 28);
INSERT INTO REDSOCIAL.AMIGOS (ID_USU, ID_AMIGO) VALUES (30, 29);
INSERT INTO REDSOCIAL.AMIGOS (ID_USU, ID_AMIGO) VALUES (30, 33);
INSERT INTO REDSOCIAL.AMIGOS (ID_USU, ID_AMIGO) VALUES (31, 28);
INSERT INTO REDSOCIAL.AMIGOS (ID_USU, ID_AMIGO) VALUES (31, 29);
INSERT INTO REDSOCIAL.AMIGOS (ID_USU, ID_AMIGO) VALUES (31, 32);
INSERT INTO REDSOCIAL.AMIGOS (ID_USU, ID_AMIGO) VALUES (31, 33);
INSERT INTO REDSOCIAL.AMIGOS (ID_USU, ID_AMIGO) VALUES (31, 34);
INSERT INTO REDSOCIAL.AMIGOS (ID_USU, ID_AMIGO) VALUES (32, 29);
INSERT INTO REDSOCIAL.AMIGOS (ID_USU, ID_AMIGO) VALUES (32, 31);
INSERT INTO REDSOCIAL.AMIGOS (ID_USU, ID_AMIGO) VALUES (32, 33);
INSERT INTO REDSOCIAL.AMIGOS (ID_USU, ID_AMIGO) VALUES (33, 28);
INSERT INTO REDSOCIAL.AMIGOS (ID_USU, ID_AMIGO) VALUES (33, 29);
INSERT INTO REDSOCIAL.AMIGOS (ID_USU, ID_AMIGO) VALUES (33, 30);
INSERT INTO REDSOCIAL.AMIGOS (ID_USU, ID_AMIGO) VALUES (33, 31);
INSERT INTO REDSOCIAL.AMIGOS (ID_USU, ID_AMIGO) VALUES (33, 32);
INSERT INTO REDSOCIAL.AMIGOS (ID_USU, ID_AMIGO) VALUES (33, 34);
INSERT INTO REDSOCIAL.AMIGOS (ID_USU, ID_AMIGO) VALUES (34, 29);
INSERT INTO REDSOCIAL.AMIGOS (ID_USU, ID_AMIGO) VALUES (34, 31);
INSERT INTO REDSOCIAL.AMIGOS (ID_USU, ID_AMIGO) VALUES (34, 33);
INSERT INTO REDSOCIAL.AMIGOS (ID_USU, ID_AMIGO) VALUES (36, 37);
INSERT INTO REDSOCIAL.AMIGOS (ID_USU, ID_AMIGO) VALUES (36, 38);
INSERT INTO REDSOCIAL.AMIGOS (ID_USU, ID_AMIGO) VALUES (37, 36);
INSERT INTO REDSOCIAL.AMIGOS (ID_USU, ID_AMIGO) VALUES (37, 38);
INSERT INTO REDSOCIAL.AMIGOS (ID_USU, ID_AMIGO) VALUES (38, 36);
INSERT INTO REDSOCIAL.AMIGOS (ID_USU, ID_AMIGO) VALUES (38, 37);
commit;

