SELECT MAX(COUNT(*))
FROM JUGADORES j
JOIN GOLES g USING (id_jugador)
GROUP BY NOMBRE;
--UNA CONSULTA CON DOS FUNCIONES DE TOTALES NO PUEDE INCLUIR
--OTRAS COLUMNAS DEBIDO A LAS RESTRICCIONES DE LOS GROUP BY
--ESTO SE SOLUCIONA CON UN SUBSELECT

SELECT NOMBRE, COUNT(*) GOLES
FROM JUGADORES j
JOIN GOLES g USING (id_jugador)
GROUP BY NOMBRE
HAVING COUNT(*)=(
    SELECT MAX(COUNT(*))
    FROM JUGADORES j
    JOIN GOLES g USING (id_jugador)
    GROUP BY NOMBRE
    );

CREATE VIEW v_pichichi (JUGADOR, GOLES) AS
--ENTRE PARENTESIS LOS NOMBRES DE LOS DATOS, LOS ALIAS
    SELECT NOMBRE, COUNT(*) GOLES
FROM JUGADORES j
JOIN GOLES g USING (id_jugador)
GROUP BY NOMBRE
HAVING COUNT(*)=(
    SELECT MAX(COUNT(*))
    FROM JUGADORES j
    JOIN GOLES g USING (id_jugador)
    GROUP BY NOMBRE
    );

SELECT * FROM V_PICHICHI;

-- CREATE OR REPLACE ELIMINA LA VISTA Y LA CREA DESPUES
--ES EL EQUIVALENTE A ALTER EN LAS VISTAS
CREATE OR REPLACE VIEW v_pichichi (ID_JUGADOR, JUGADOR, GOLES) AS
--ENTRE PARENTESIS LOS NOMBRES DE LOS DATOS, LOS ALIAS
    SELECT ID_JUGADOR ,NOMBRE, COUNT(*) GOLES
FROM JUGADORES j
JOIN GOLES g USING (id_jugador)
GROUP BY ID_JUGADOR, NOMBRE
HAVING COUNT(*)=(
    SELECT MAX(COUNT(*))
    FROM JUGADORES j
    JOIN GOLES g USING (id_jugador)
    GROUP BY  NOMBRE
    );

--LAS VISTAS PUEDEN SER USADAS COMO TABLAS
SELECT e.NOMBRE, JUGADOR, GOLES
FROM EQUIPOS e
JOIN JUGADORES j USING (ID_EQUIPO)
JOIN V_PICHICHI v USING (ID_JUGADOR);


--ESTA CONSULTA DEVUELVE EL JUGADOR QUE ESTE EN LA
-- TABLA EQUIPOS+JUGAORES Y ADEMAS EN LA VISTA V_PICHICHI
SELECT e.NOMBRE, j.NOMBRE
FROM EQUIPOS e
JOIN JUGADORES j USING (ID_EQUIPO)
WHERE ID_JUGADOR IN (SELECT ID_JUGADOR FROM V_PICHICHI);

--ESTA CONSULTA HACE LO MISMO QUE LA ANTERIOR CAMBIANDO IN POR =ANY
--SI EL SUBSELECT DEVOLVIESE UN SOLO VALOR SE PODRIA USAR UN =
--NO OBSTANTE, COMO PUEDE HABER VARIOS JUGADORES CON EL MISMO NÚMERO DE JUGADORES
--ESTE PUEDE DEVOLVER UNA LISTA Y POR ESO HAY QUE USAR IN O =ANY
SELECT e.NOMBRE, j.NOMBRE
FROM EQUIPOS e
JOIN JUGADORES j USING (ID_EQUIPO)
WHERE ID_JUGADOR = ANY (SELECT ID_JUGADOR FROM V_PICHICHI);