CREATE DATABASE PROYECTO_RESERVAS;
USE PROYECTO_RESERVAS;
CREATE USER ADMIN_RESERVAS IDENTIFIED BY 'A12345a';
GRANT SELECT,INSERT,DELETE ON * TO ADMIN_RESERVAS;

CREATE TABLE SALAS(
    CODIGO    CHAR(3),
    NOMBRE    VARCHAR(50) NOT NULL ,
    PRIMARY KEY salas_pk (CODIGO),
    CONSTRAINT salas_uk1 UNIQUE (NOMBRE)
);

CREATE TABLE DEPARTAMENTOS(
    CODIGO    CHAR(3),
    NOMBRE    VARCHAR(50) NOT NULL ,
    PRIMARY KEY   salas_pk (CODIGO),
    CONSTRAINT    salas_uk1 UNIQUE (NOMBRE)
);

CREATE TABLE RESERVAS(
    COD_RESERVAS        CHAR(3),
    COD_SALAS           CHAR(3),
    COD_DEPARTAMENTO    CHAR(3)     NOT NULL,
    FECHA_INICIO        DATETIME    NOT NULL,
    FECHA_FIN           DATETIME    NOT NULL,
    PRIMARY KEY     reservas_pk  (COD_RESERVAS,COD_SALAS,COD_DEPARTAMENTO),
    FOREIGN KEY     reservas_fk1 (COD_SALAS) REFERENCES SALAS(CODIGO) ON DELETE CASCADE,
    CONSTRAINT      reservas_uk1 UNIQUE (FECHA_INICIO,FECHA_FIN)
);

/*
TIEMPO es un dato calculable entre fecha inicio y fecha fin
*/